### ISSUE TITLE
Getting all white blocks

### ISSUE THREAD

**Issue by bhavik-goyal** [charithmaddoju/Lights-Out#2]
After clicking on the application link, I am getting all the blocks as white which makes easy to win as I just click any block and re-click it, I'll win without any efforts.
![White blocks](https://github.com/charithmaddoju/Lights-Out/assets/113616231/e15564fb-2e83-471c-bcdf-04e68c71303f)

**Comment by charithmaddoju** [comment]
I have fixed this in : d98198eecd55de3efb73edcf032e6c4d7f396949
